language: go
sudo: false
go:
- 1.7.4
- 1.8.1  
install:
- go get -v github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get -d -t -v ./...
- go build -v ./...
script:
- go vet ./...
- $HOME/gopath/bin/golint .
- go test -v -race ./...
- go test -v -covermode=count -coverprofile=cov.out
- $HOME/gopath/bin/goveralls -coverprofile=cov.out -service=travis-ci -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: azR062N6029b8ZUPlligQdAvq5pajX1xbAOEyKTzDS6HP4/TfERQkiMo+QiVlDPzdQujKUNdG/HGkv6BQ2OfW3RQW4K/HbphpAVkNIxpRi1qH/T0rOSenUMwTkyZa5M4I3zyRqt1uRXVwkqbg+xHnXQp5S3mXt1QQRYYF6ffpt3wlUgkSPvrXswKQIXPObyNTNFMxEIYXGsroEOpKqKBgV68cLHKt3OsSZyYcnIXSP/jbKg5iaRsoc/3BkeWH7AvjUCt8NQOZtrUAhWC6xcjFNrGboQsK5xPEinw47n4V5Hb3A1yIk+GBpDfE/loKv/KGxi4uf98HXuKVSkRrKPz/IOrxoeaUfiAKC6DnnqgJrLY3bkvVBb9EA1M5wrNxMknGQG1AFP8nAO1bhKp6u+e78A97FpTmcE1+sqR+DL5kKuySqjaFqv4Mauugle3+jPRnrKV9myiILd6X7lmN4RiSDRZWd+C8KGaTqJIBu2JxZzsHeNAFXne4gWX0RZnRT1p/ncmT8V3iOyzLJzUvg2epgSB0bKulvXaSRIvXlXPsu80AofI27eLJjvd1dRbFHWpw8ZhZgUilUuSPJe/6thlvHipIsXOdEysgocpyBKvo/utE7OQHj99wcSBnBb4P7f4L+UFDwmX78d+fO3GN84vf1YHUh5BvDb/d8bssbOqu0E=
